#!/bin/bash

# A sample Bash script to fix the max users watching files
# NOTE: only works on arch linux

echo fs.inotify.max_user_watches=524288 | sudo tee /etc/sysctl.d/40-max-user-watches.conf && sudo sysctl --system
